[project]
name = "resume-builder"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aioboto3>=15.5.0",
    "django>=6.0.4",
    "django-environ>=0.12.0",
    "django-ninja>=1.6.2",
    "httpx>=0.28.1",
    "pydantic[email]>=2.13.3",
    "uvicorn>=0.46.0",
    "uvloop>=0.22.1",
    "weasyprint>=68.1",
]

[dependency-groups]
dev = [
    "black>=26.3.1",
]
